repos:
- hooks:
  - args:
    - --in-place
    - --remove-all-unused-imports
    - --expand-star-imports
    - --remove-duplicate-keys
    - --remove-unused-variables
    exclude: .*/__init__.py
    id: autoflake
  repo: https://github.com/myint/autoflake
  rev: v1.4
- hooks:
  - entry: flake8
    id: flake8
    language: system
    name: flake8
    types:
    - python
  repo: local
- hooks:
  - args:
    - --profile
    - black
    id: isort
  repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.4.2
- hooks:
  - entry: mypy
    id: mypy
    language: system
    name: mypy
    types:
    - python
  repo: local
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.0
