version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: local.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_SERVER=database
      - POSTGRES_DB=escoladb
      - BACKEND_CORS_ORIGINS=["http://localhost:8000", "https://localhost:8000", "http://localhost", "https://localhost"]
    ports:
      - "8000:8000"
  database:
    image: postgres:12
    hostname: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
