"""Add table Titulo e Professor

Revision ID: 1bec38b7baf7
Revises: 58156ec7c26f
Create Date: 2023-01-08 23:47:17.000275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bec38b7baf7'
down_revision = '58156ec7c26f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titulo',
    sa.Column('id_titulo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_titulo')
    )
    op.create_index(op.f('ix_titulo_id_titulo'), 'titulo', ['id_titulo'], unique=False)
    op.create_index(op.f('ix_titulo_tx_descricao'), 'titulo', ['tx_descricao'], unique=False)
    op.create_table('professor',
    sa.Column('id_professor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_titulo', sa.Integer(), nullable=True),
    sa.Column('tx_nome', sa.String(), nullable=True),
    sa.Column('tx_sexo', sa.String(), nullable=True),
    sa.Column('tx_estado_civil', sa.String(), nullable=True),
    sa.Column('dt_nascimento', sa.String(), nullable=True),
    sa.Column('tx_telefone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_titulo'], ['titulo.id_titulo'], ),
    sa.PrimaryKeyConstraint('id_professor')
    )
    op.create_index(op.f('ix_professor_dt_nascimento'), 'professor', ['dt_nascimento'], unique=False)
    op.create_index(op.f('ix_professor_id_professor'), 'professor', ['id_professor'], unique=False)
    op.create_index(op.f('ix_professor_tx_estado_civil'), 'professor', ['tx_estado_civil'], unique=False)
    op.create_index(op.f('ix_professor_tx_nome'), 'professor', ['tx_nome'], unique=False)
    op.create_index(op.f('ix_professor_tx_sexo'), 'professor', ['tx_sexo'], unique=False)
    op.create_index(op.f('ix_professor_tx_telefone'), 'professor', ['tx_telefone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professor_tx_telefone'), table_name='professor')
    op.drop_index(op.f('ix_professor_tx_sexo'), table_name='professor')
    op.drop_index(op.f('ix_professor_tx_nome'), table_name='professor')
    op.drop_index(op.f('ix_professor_tx_estado_civil'), table_name='professor')
    op.drop_index(op.f('ix_professor_id_professor'), table_name='professor')
    op.drop_index(op.f('ix_professor_dt_nascimento'), table_name='professor')
    op.drop_table('professor')
    op.drop_index(op.f('ix_titulo_tx_descricao'), table_name='titulo')
    op.drop_index(op.f('ix_titulo_id_titulo'), table_name='titulo')
    op.drop_table('titulo')
    # ### end Alembic commands ###
