"""Adicionar tabela Aluno

Revision ID: 58156ec7c26f
Revises: 
Create Date: 2022-11-04 03:12:11.005368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58156ec7c26f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id_aluno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_nome', sa.String(), nullable=True),
    sa.Column('tx_sexo', sa.String(), nullable=True),
    sa.Column('dt_nascimento', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_aluno')
    )
    op.create_index(op.f('ix_aluno_dt_nascimento'), 'aluno', ['dt_nascimento'], unique=False)
    op.create_index(op.f('ix_aluno_id_aluno'), 'aluno', ['id_aluno'], unique=False)
    op.create_index(op.f('ix_aluno_tx_nome'), 'aluno', ['tx_nome'], unique=False)
    op.create_index(op.f('ix_aluno_tx_sexo'), 'aluno', ['tx_sexo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aluno_tx_sexo'), table_name='aluno')
    op.drop_index(op.f('ix_aluno_tx_nome'), table_name='aluno')
    op.drop_index(op.f('ix_aluno_id_aluno'), table_name='aluno')
    op.drop_index(op.f('ix_aluno_dt_nascimento'), table_name='aluno')
    op.drop_table('aluno')
    # ### end Alembic commands ###
